### ISSUE TITLE
Test is full

### ISSUE THREAD

**Issue by Raffatronic** [MicrosoftDocs/windowsserverdocs.de-de#13]
Dear MS 
I would love to test this one in our Office -&gt; We are a large account reseller. Yet the testgroup is full. 
Could you provide me a code to test? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3d21e96b-c8a6-7f9f-76e1-62ee4fbde62b
* Version Independent ID: 5530201e-2ff5-19de-5990-1a996cf5ef2e
* Content: [Erste Schritte mit dem iOS-Client](https://docs.microsoft.com/de-de/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by srvbpigh** [comment]
Hello, @Raffatronic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Raffatronic, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3907. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
