### ISSUE TITLE
MT option in newer versions

### ISSUE THREAD

**Issue by Mac-Chiato** [MicrosoftDocs/windowsserverdocs.de-de#19]
Its not clear if the option /MT is available in newer versions than Windows 7 / Windows Server 2008R2
Newer versions should also be described here, as they are supported

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @Mac-Chiato
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Mac-Chiato, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4242. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
