### ISSUE TITLE
Makeprofile.ps1 

### ISSUE THREAD

**Issue by APACIUS** [MicrosoftDocs/windowsserverdocs.de-de#22]
in the makeprofile.ps1 there are additional ` that needs to be removed.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Konfigurieren von Windows 10-Client immer auf VPN-Verbindungen](https://docs.microsoft.com/de-de/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections?source=docs#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by srvbpigh** [comment]
Hello, @APACIUS
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @APACIUS, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4380. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
