### ISSUE TITLE
Example 2 slightly misleading

### ISSUE THREAD

**Issue by longwolf** [MicrosoftDocs/windowsserverdocs.de-de#7]
Actually, the 2nd example

md \Taxes\Property\Current

is equivalent to either

md \Taxes
cd \Taxes 
md Property
cd Property
md Current
cd ..
cd ..

or

md \Taxes
md \Taxes\Property
md \Taxes\Property\Current

(md never changes the current directory)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 111e6344-0556-e6a6-3001-db3ea4aa55d7
* Version Independent ID: 4d5f387d-f50a-6c4a-b628-a17c368e16ff
* Content: [md](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/md#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/md.md](https://github.com/MicrosoftDocs/windowsserverdocs.de-de/blob/live/WindowsServerDocs/administration/windows-commands/md.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @longwolf
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @longwolf 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3609

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
